config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, :length, :music_file, presence: true
    mount_uploader :music_file, MusicFileUploader
    has_many :music_file_types
end

app/models/music_file_type.rb
class MusicFileType < ApplicationRecord
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    send_file(Rails.root.join('public', 'uploads', 'item', 'music_file', @item.title))
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
      redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :length, :url, :usd, :rmb, :music_type, :music_file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Music Manager
        <br>Design by
        <a href="#" target=_new>Miao</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Music Manager</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("登入", '#') %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
<div class="form-group">
    <%= f.input :title, label: '音乐名称', placeholder: '请填写音乐名称', input_html: { class: "form-control"} %>
    <%= f.input :length, label: '音乐长度', placeholder: '01:30', input_html: { class: "form-control"} %>
    <%= f.input :url, label: '原地址', placeholder: '请填写素材原始地址', input_html: { class: "form-control"} %>
    <%= f.input :usd, label: 'USD', placeholder: '20', input_html: { class: "form-control"} %>
    <%= f.input :rmb, label: 'RMB', placeholder: '120', input_html: { class: "form-control"} %>
    <%= f.collection_radio_buttons :music_type, [[true, '音乐'] ,[false, '音效']], :first, :last %>
    <%= f.input :music_file, label: '选择音乐', as: :file %>
</div>
<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/items/_index_list.html.erb
<table class="table table-hover">
    <thead>
        <tr>
            <td>音乐序号</td>
            <td>音乐名称</td>
            <td>长度</td>
            <td>素材网址</td>
            <td>美元价格</td>
            <td>人民币价格</td>
            <td>文件类型</td>
        </tr>
    </thead>
    <tbody>
        <% @items.each do |item| %>
        <tr>
            <td><%= item.id %></td>
            <td><%= item.title %></td>
            <td><%= item.length %></td>
            <td><%= item.url %></td>
            <td><%= item.usd %></td>
            <td><%= item.rmb %></td>
            <td><% if item.music_type == true %>
                音乐
            <% else %>
                音效
                <% end %>
            </td>
            <td>
                <audio controls>
                    <source src="<%= item.music_file %>" type="audio/wav">
                </audio>
                <%= link_to("下载", item_path(item), class: "btn btn-sm btn-default")%>
                <%= link_to("编辑", edit_item_path(item), class: "btn btn-sm btn-default")%>
                <%= link_to("删除", item_path(item),    class: "btn btn-sm btn-default",
                      method: :delete, data: { confirm: "你真的要删除吗?" } )%>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/items/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑这个音乐</h2>
    <hr>
    <%= render "form" %>
</div>

app/views/items/index.html.erb
<div class="col-md-12">
    <div class="group">
        <%= link_to("上传素材", new_item_path, class: "btn btn-primary pull-right") %>
    </div>
    <div class="col-md-12">
        <%= render "index_list" %>
    </div>
</div>

app/views/items/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>上传音乐</h2>
    <hr>
    <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Music Manager</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        </script>

    </head>

    <body>
        <div class="continer-fluid">
            <%= render "common/navbar" %>
            <%= yield %>
            <%= render "common/footer" %>
        </div>
    </body>
</html>